var pdfFiller   = require('pdffiller'),
	fs = require('fs-extra'),
	path = require('path'),
	q = require('q'),
	_ = require('lodash'),
	home = process.env.HOME || process.env.USERPROFILE,
	PDFCHARAKTERBOGEN = function(){
		var formFile = path.join(process.cwd(),'res', 'charakterbogen_raw.pdf'),
			destPDFPath = path.join(home,'splitterfinder'),
			fdfTemplate, temp, 
			checkDirectory = function(){
				try{
					var check = fs.statSync(destPDFPath);
				} catch (e){
					if(e.code === 'ENOENT'){
						fs.mkdirSync(destPDFPath);
					}
				}
				
			},
			getTemplate = function(){
				var def = q.defer();
				pdfFiller.generateFDFTemplate(formFile, null, function(err, formData){
					def.resolve(formData);
				});
				return def.promise;
			}, mapTemplate = function(data){
				var map = {
					
					"Name": data.name,
					"Ausbildung": data.ausbildung,
					"Kultur": data.kultur,
					"Abstammung": data.abstammung,
					"Rasse": data.rasse,
					"Geschlecht": data.geschlecht,
					"Haarfarbe": data.haarfarbe,
					"Körpergröße": data.koerpergroesse,
					"Mondzeichen": data.mondzeichen,
					"Augenfarbe": data.augenfarbe,
					"Gewicht": data.gewicht,
					"Hautfarbe": data.hautfarbe,
					"Geburtsort": data.geburtsort,
					"Sprachen": data.sprachen.shift(),
					"Grad 1": "",
					"Grad 2": "",
					"Kulturkunde": data.kulturkunde.join(','),
					
					"StärkenRow1": __getColumnOfRow(0,0,data.staerken),
					"WirkungRow1": __getColumnOfRow(0,1,data.staerken),
					"StärkenRow2": __getColumnOfRow(1,0,data.staerken),
					"WirkungRow2": __getColumnOfRow(1,1,data.staerken),
					"StärkenRow3": __getColumnOfRow(2,0,data.staerken),
					"WirkungRow3": __getColumnOfRow(2,1,data.staerken),
					"StärkenRow4": __getColumnOfRow(3,0,data.staerken),
					"WirkungRow4": __getColumnOfRow(3,1,data.staerken),
					"StärkenRow5": __getColumnOfRow(4,0,data.staerken),
					"WirkungRow5": __getColumnOfRow(4,1,data.staerken),
					"StärkenRow6": __getColumnOfRow(5,0,data.staerken),
					"WirkungRow6": __getColumnOfRow(5,1,data.staerken),
					"StärkenRow7": __getColumnOfRow(6,0,data.staerken),
					"WirkungRow7": __getColumnOfRow(6,1,data.staerken),
					"StärkenRow8": __getColumnOfRow(7,0,data.staerken),
					"WirkungRow8": __getColumnOfRow(7,1,data.staerken),
					"StärkenRow9": __getColumnOfRow(8,0,data.staerken),
					"WirkungRow9": __getColumnOfRow(8,1,data.staerken),
					
					
					"AusrüstungRow1": __getColumnOfRow(0,0,data.ausruestung),
					"LastRow1": __getColumnOfRow(0,1,data.ausruestung),
					"AusrüstungRow2": __getColumnOfRow(1,0,data.ausruestung),
					"LastRow2": __getColumnOfRow(1,1,data.ausruestung),
					"AusrüstungRow3": __getColumnOfRow(2,0,data.ausruestung),
					"LastRow3": __getColumnOfRow(2,1,data.ausruestung),
					"AusrüstungRow4": __getColumnOfRow(3,0,data.ausruestung),
					"LastRow4": __getColumnOfRow(3,1,data.ausruestung),
					"AusrüstungRow5": __getColumnOfRow(4,0,data.ausruestung),
					"LastRow5": __getColumnOfRow(4,1,data.ausruestung),
					"AusrüstungRow6": __getColumnOfRow(5,0,data.ausruestung),
					"LastRow6": __getColumnOfRow(5,1,data.ausruestung),
					"AusrüstungRow7": __getColumnOfRow(6,0,data.ausruestung),
					"LastRow7": __getColumnOfRow(6,1,data.ausruestung),
					"AusrüstungRow8": __getColumnOfRow(7,0,data.ausruestung),
					"LastRow8": __getColumnOfRow(7,1,data.ausruestung),
					"AusrüstungRow9": __getColumnOfRow(8,0,data.ausruestung),
					"LastRow9": __getColumnOfRow(8,1,data.ausruestung),
					
					"AusrüstungRow1_2": __getColumnOfRow(9,0,data.ausruestung),
					"LastRow1_2": __getColumnOfRow(9,1,data.ausruestung),
					"AusrüstungRow2_2": __getColumnOfRow(10,0,data.ausruestung),
					"LastRow2_2": __getColumnOfRow(10,1,data.ausruestung),
					"AusrüstungRow3_2": __getColumnOfRow(11,0,data.ausruestung),
					"LastRow3_2": __getColumnOfRow(11,1,data.ausruestung),
					"AusrüstungRow4_2": __getColumnOfRow(12,0,data.ausruestung),
					"LastRow4_2": __getColumnOfRow(12,1,data.ausruestung),
					"AusrüstungRow5_2": __getColumnOfRow(13,0,data.ausruestung),
					"LastRow5_2": __getColumnOfRow(13,1,data.ausruestung),
					"AusrüstungRow6_2": __getColumnOfRow(14,0,data.ausruestung),
					"LastRow6_2": __getColumnOfRow(14,1,data.ausruestung),
					"AusrüstungRow7_2": __getColumnOfRow(15,0,data.ausruestung),
					"LastRow7_2": __getColumnOfRow(15,1,data.ausruestung),
					"AusrüstungRow8_2": __getColumnOfRow(16,0,data.ausruestung),
					"LastRow8_2": __getColumnOfRow(16,1,data.ausruestung),
					"AusrüstungRow9_2": __getColumnOfRow(17,0,data.ausruestung),
					"LastRow9_2": __getColumnOfRow(17,1,data.ausruestung),
					
					"MerkmaleSTÄ":"",
					
					"RüstungenRow1": __getColumnOfRow(0,0,data.ruestung),
					"VTDRow1": __getColumnOfRow(0,1,data.ruestung),
					"SRRow1": __getColumnOfRow(0,2,data.ruestung),
					"BehRow1": __getColumnOfRow(0,3,data.ruestung),
					"TickRow1": __getColumnOfRow(0,4,data.ruestung),
					"RüstungenRow2": __getColumnOfRow(1,0,data.ruestung),
					"VTDRow2": __getColumnOfRow(1,1,data.ruestung),
					"SRRow2": __getColumnOfRow(1,2,data.ruestung),
					"BehRow2": __getColumnOfRow(1,3,data.ruestung),
					"TickRow2": __getColumnOfRow(1,4,data.ruestung),
					"RüstungenRow3": __getColumnOfRow(2,0,data.ruestung),
					"VTDRow3": __getColumnOfRow(2,1,data.ruestung),
					"SRRow3": __getColumnOfRow(2,2,data.ruestung),
					"BehRow3": __getColumnOfRow(2,3,data.ruestung),
					"TickRow3": __getColumnOfRow(2,4,data.ruestung),
					"RüstungenRow4": __getColumnOfRow(3,0,data.ruestung),
					"VTDRow4": __getColumnOfRow(3,1,data.ruestung),
					"SRRow4": __getColumnOfRow(3,2,data.ruestung),
					"BehRow4": __getColumnOfRow(3,3,data.ruestung),
					"TickRow4": __getColumnOfRow(3,4,data.ruestung),
					
					"VTDSumme": __getSumOfColumn(1,data.ruestung),
					"SRSumme": __getSumOfColumn(2,data.ruestung),
					"BehSumme": __getSumOfColumn(3,data.ruestung),
					"TickSumme": __getSumOfColumn(4,data.ruestung),
					/*
					"ZauberRow1":"",
					"SchuleRow1":"",
					"GradRow1":"",
					"SchwRow1":"",
					"FokusRow1":"",
					"ZDRow1":"",
					"RWRow1":"",
					"WDRow1":"",
					"VerstärkungRow1":"",
					"SeiteRow1":"",
					"Kan PktRow1":"",
					"ZauberRow2":"",
					"SchuleRow2":"",
					"GradRow2":"",
					"SchwRow2":"",
					"FokusRow2":"",
					"ZDRow2":"",
					"RWRow2":"",
					"WDRow2":"",
					"VerstärkungRow2":"",
					"SeiteRow2":"",
					"Kan PktRow2":"",
					"ZauberRow3":"",
					"SchuleRow3":"",
					"GradRow3":"",
					"SchwRow3":"",
					"FokusRow3":"",
					"ZDRow3":"",
					"RWRow3":"",
					"WDRow3":"",
					"VerstärkungRow3":"",
					"SeiteRow3":"",
					"Kan PktRow3":"",
					"ZauberRow4":"",
					"SchuleRow4":"",
					"GradRow4":"",
					"SchwRow4":"",
					"FokusRow4":"",
					"ZDRow4":"",
					"RWRow4":"",
					"WDRow4":"",
					"VerstärkungRow4":"",
					"SeiteRow4":"",
					"Kan PktRow4":"",
					"ZauberRow5":"",
					"SchuleRow5":"",
					"GradRow5":"",
					"SchwRow5":"",
					"FokusRow5":"",
					"ZDRow5":"",
					"RWRow5":"",
					"WDRow5":"",
					"VerstärkungRow5":"",
					"SeiteRow5":"",
					"Kan PktRow5":"",
					"ZauberRow6":"",
					"SchuleRow6":"",
					"GradRow6":"",
					"SchwRow6":"",
					"FokusRow6":"",
					"ZDRow6":"",
					"RWRow6":"",
					"WDRow6":"",
					"VerstärkungRow6":"",
					"SeiteRow6":"",
					"Kan PktRow6":"",
					"ZauberRow7":"",
					"SchuleRow7":"",
					"GradRow7":"",
					"SchwRow7":"",
					"FokusRow7":"",
					"ZDRow7":"",
					"RWRow7":"",
					"WDRow7":"",
					"VerstärkungRow7":"",
					"SeiteRow7":"",
					"Kan PktRow7":"",
					"ZauberRow8":"",
					"SchuleRow8":"",
					"GradRow8":"",
					"SchwRow8":"",
					"FokusRow8":"",
					"ZDRow8":"",
					"RWRow8":"",
					"WDRow8":"",
					"VerstärkungRow8":"",
					"SeiteRow8":"",
					"Kan PktRow8":"",
					"ZauberRow9":"",
					"SchuleRow9":"",
					"GradRow9":"",
					"SchwRow9":"",
					"FokusRow9":"",
					"ZDRow9":"",
					"RWRow9":"",
					"WDRow9":"",
					"VerstärkungRow9":"",
					"SeiteRow9":"",
					"Kan PktRow9":"",
					"ZauberRow10":"",
					"SchuleRow10":"",
					"GradRow10":"",
					"SchwRow10":"",
					"FokusRow10":"",
					"ZDRow10":"",
					"RWRow10":"",
					"WDRow10":"",
					"VerstärkungRow10":"",
					"SeiteRow10":"",
					"Kan PktRow10":"",
					"ZauberRow11":"",
					"SchuleRow11":"",
					"GradRow11":"",
					"SchwRow11":"",
					"FokusRow11":"",
					"ZDRow11":"",
					"RWRow11":"",
					"WDRow11":"",
					"VerstärkungRow11":"",
					"SeiteRow11":"",
					"Kan PktRow11":"",
					"ZauberRow12":"",
					"SchuleRow12":"",
					"GradRow12":"",
					"SchwRow12":"",
					"FokusRow12":"",
					"ZDRow12":"",
					"RWRow12":"",
					"WDRow12":"",
					"VerstärkungRow12":"",
					"SeiteRow12":"",
					"Kan PktRow12":"",
					"ZauberRow13":"",
					"SchuleRow13":"",
					"GradRow13":"",
					"SchwRow13":"",
					"FokusRow13":"",
					"ZDRow13":"",
					"RWRow13":"",
					"WDRow13":"",
					"VerstärkungRow13":"",
					"SeiteRow13":"",
					"Kan PktRow13":"",
					"ZauberRow14":"",
					"SchuleRow14":"",
					"GradRow14":"",
					"SchwRow14":"",
					"FokusRow14":"",
					"ZDRow14":"",
					"RWRow14":"",
					"WDRow14":"",
					"VerstärkungRow14":"",
					"SeiteRow14":"",
					"Kan PktRow14":"",
					"ZauberRow15":"",
					"SchuleRow15":"",
					"GradRow15":"",
					"SchwRow15":"",
					"FokusRow15":"",
					"ZDRow15":"",
					"RWRow15":"",
					"WDRow15":"",
					"VerstärkungRow15":"",
					"SeiteRow15":"",
					"Kan PktRow15":"",
					*/
					"Grad 4":"",
					"Splitterpunkte":"",
					"Sprachen_2":data.sprachen.splice(1,data.sprachen.length).join(','),
					"Schwächen_1":getFirstTwo(data.schwaechen),
					"Schwächen_2":getMiddleTwo(data.schwaechen),
					"Schwächen_3":getLastTwo(data.schwaechen),
					"EP_Gesamt":data.erfahrungspunkte.gesamt,
					"EP_eingesetzt":data.erfahrungspunkte.eingesetzt,
					"BEW_Start":"",
					"INT_Start":"",
					"KON_Start":"",
					"MYS_Start":"",
					"VER_Start":"",
					"STÄ_Start":"",
					"WIL_Start":"",
					"AUS_Start":"",
					"AUS_mod":"",
					"BEW_mod":"",
					"INT_mod":"",
					"KON_mod":"",
					"MYS_mod":"",
					"STÄ_mod":"",
					"VER_mod":"",
					"WIL_mod":"",
					"GK_Wert": data.abgeleitet.GK,
					"GK_mod":"",
					"GK_temp":"",
					"GSW_Wert": data.abgeleitet.GSW,
					"GSW_mod":"",
					"GSW_temp":"",
					"INI_Wert": data.abgeleitet.INI,
					"INI_mod":"",
					"INI_temp":"",
					"LP_Wert": data.abgeleitet.LP,
					"LP_mod":"",
					"LP_temp":"",
					"FO_Wert": data.abgeleitet.FO,
					"FO_mod":"",
					"FO_temp":"",
					"VTD_Wert": data.abgeleitet.VTD,
					"VTD_mod":"",
					"VTD_temp":"",
					"GW_Wert": data.abgeleitet.GW,
					"GW_mod":"",
					"KW_Wert": data.abgeleitet.KW,
					"KW_mod":"",
					"KW_temp":"",
					"BEW_Wert": data.attribute.BEW,
					"EP_offen": data.erfahrungspunkte.offen,
					"EP_für_nächsten_Heldengrad":"",
					"maximale Fertigkeitspunkte":"",
					"maximales Attribut":"",
					"Heldengrad":"",
					"STÄ_Wert": data.attribute.STA,
					"MYS_Wert": data.attribute.MYS,
					"VER_Wert": data.attribute.VER,
					"AUS_Wert": data.attribute.AUS,
					"WIL_Wert": data.attribute.WIL,
					"INT_Wert": data.attribute.INT,
					"KON_Wert": data.attribute.KON,
					"Akrobatik_Wert": data.fertigkeiten.akrobatik.wert,
					"Akrobatik_Punkte": data.fertigkeiten.akrobatik.punkte,
					"Akrobatik_mod":"",
					"Alchemie_Wert": data.fertigkeiten.alchemie.wert,
					"Alchemie_Punkte": data.fertigkeiten.alchemie.punkte,
					"Alchemie_mod":"",
					"Anführen_Wert": data.fertigkeiten.anfuehren.wert,
					"Anführen_Punkte": data.fertigkeiten.anfuehren.punkte,
					"Anführen_mod":"",
					"Arkane_Kunde_Wert": data.fertigkeiten.arkaneKunde.wert,
					"Arkane_Kunde_Punkte": data.fertigkeiten.arkaneKunde.punkte,
					"Arkane_Kunde_mod":"",
					"Athletik_Wert": data.fertigkeiten.athletik.wert,
					"Athletik_Punkte": data.fertigkeiten.athletik.punkte,
					"Athletik_mod": "",
					"Darbietung_Wert": data.fertigkeiten.darbietung.wert,
					"Darbietung_Punkte": data.fertigkeiten.darbietung.punkte,
					"Darbietung_mod":"",
					"Diplomatie_Wert": data.fertigkeiten.diplomatie.wert,
					"Diplomatie_Punkte": data.fertigkeiten.diplomatie.punkte,
					"Edelhandwerk_Wert":data.fertigkeiten.edelhandwerk.wert,
					"Edelhandwerk_Punkte": data.fertigkeiten.edelhandwerk.punkte,
					"Edelhandwerk_mod":"",
					"Diplomatie_mod":"",
					"Empathie_Wert": data.fertigkeiten.empathie.wert,
					"Empathie_Punkte": data.fertigkeiten.empathie.punkte,
					"Empathie_mod":"",
					"Entschlossenheit_Wert": data.fertigkeiten.entschlossenheit.wert,
					"Entschlossenheit_Punkte": data.fertigkeiten.entschlossenheit.punkte,
					"Entschlossenheit_mod":"",
					"Fingerfertigkeit_Wert": data.fertigkeiten.fingerfertigkeit.wert,
					"Fingerfertigkeit_Punkte": data.fertigkeiten.fingerfertigkeit.punkte,
					"Fingerfertigkeit_mod":"",
					"Geschichte&Mythen_Wert": data.fertigkeiten.geschichteUndMythen.wert,
					"Geschichte&Mythen_Punkte": data.fertigkeiten.geschichteUndMythen.punkte,
					"Geschichte&Mythen_mod":"",
					"Handwerk_Wert": data.fertigkeiten.handwerk.wert,
					"Handwerk_Punkte": data.fertigkeiten.handwerk.punkte,
					"Handwerk_mod":"",
					"Heilkunde_Wert": data.fertigkeiten.heilkunde.wert,
					"Heilkunde_Punkte": data.fertigkeiten.heilkunde.punkte,
					"Heilkunde_mod":"",
					"Heimlichkeit_Wert": data.fertigkeiten.heimlichkeit.wert,
					"Heimlichkeit_Punkte": data.fertigkeiten.heimlichkeit.punkte,
					"Heimlichkeit_mod":"",
					"Jagdkunst_Wert": data.fertigkeiten.jagdkunst.wert,
					"Jagdkunst_Punkte": data.fertigkeiten.jagdkunde.punkte,
					"Jagdkunst_mod":"",
					"Länderkunde_Wert":"",
					"Länderkunde_Punkte":"",
					"Länderkunde_mod":"",
					"Naturkunde_Wert":"",
					"Naturkunde_Punkte":"",
					"Naturkunde_mod":"",
					"Redegewandtheit_Wert":"",
					"Redegewandtheit_Punkte":"",
					"Redegewandtheit_mod":"",
					"Schlösser&Fallen_Wert":"",
					"Schlösser&Fallen_Punkte":"",
					"Schlösser&Fallen_mod":"",
					"Schwimmen_Wert":"",
					"Schwimmen_Punkte":"",
					"Schwimmen_mod":"",
					"Seefahrt_Wert":"",
					"Seefahrt_Punkte":"",
					"Seefahrt_mod":"",
					"Straßenkunde_Wert":"",
					"Straßenkunde_Punkte":"",
					"Straßenkunde_mod":"",
					"Tierführung_Wert":"",
					"Tierführung_Punkte":"",
					"Tierführung_mod":"",
					"Überleben_Wert":"",
					"Überleben_Punkte":"",
					"Überleben_mod":"",
					"Wahrnehmung_Wert":"",
					"Wahrnehmung_Punkte":"",
					"Wahrnehmung_mod":"",
					"Zähigkeit_Wert":"",
					"Zähigkeit_Punkte":"",
					"Zähigkeit_mod":"",
					"M.0.0":"",
					"M.0.1":"",
					"M.0.2":"",
					"M.1.0":"",
					"M.1.1":"",
					"M.1.2":"",
					"M.2.0":"",
					"M.2.1":"",
					"M.2.2":"",
					"M.3.0":"",
					"M.3.1":"",
					"M.3.2":"",
					"M.4.0":"",
					"M.4.1":"",
					"M.4.2":"",
					"M.5.0":"",
					"M.5.1":"",
					"M.5.2":"",
					"M.6.0":"",
					"M.6.1":"",
					"M.6.2":"",
					"M.7.0":"",
					"M.7.1":"",
					"M.7.2":"",
					"M.8.0":"",
					"M.8.1":"",
					"M.8.2":"",
					"M.9.0":"",
					"M.9.1":"",
					"M.9.2":"",
					"M.10.0":"",
					"M.10.1":"",
					"M.10.2":"",
					"M.11.0":"",
					"M.11.1":"",
					"M.11.2":"",
					"M.12.0":"",
					"M.12.1":"",
					"M.12.2":"",
					"M.13.0":"",
					"M.13.1":"",
					"M.13.2":"",
					"M.14.0":"",
					"M.14.1":"",
					"M.14.2":"",
					"M":"",
					"N.0":"",
					"N.1":"",
					"N.2":"",
					"N.3":"",
					"N.4":"",
					"N.5":"",
					"N.6":"",
					"N.7":"",
					"N.8":"",
					"N.9":"",
					"N.10":"",
					"N.11":"",
					"N.12":"",
					"N.13":"",
					"N.14":"",
					"R.0.0":"",
					"R.0.1":"",
					"R.1.0":"",
					"R.1.1":"",
					"R.2.0":"",
					"R.2.1":"",
					"R.3.0":"",
					"R.3.1":"",
					"R.4.0":"",
					"R.4.1":"",
					"R.5.0":"",
					"R.5.1":"",
					"R.6.0":"",
					"R.6.1":"",
					"R.7.0":"",
					"R.7.1":"",
					"R.8.0":"",
					"R.8.1":"",
					"R.9.0":"",
					"R.9.1":"",
					"R":"",
					"Handgemenge_Punkte":"",
					"Hiebwaffen_Punkte":"",
					"Kettenwaffen_Punkte":"",
					"Klingenwaffen_Punkte":"",
					"Stangenwaffen_Punkte":"",
					"Schusswaffen_Punkte":"",
					"Wurfwaffen_Punkte":"",
					"Waffenlos_mod":"",
					"Waffenlos_Wert":"",
					"Waffe_1":"",
					"Waffe_2":"",
					"Waffe_3":"",
					"Waffe_4":"",
					"Schild":"",
					"Waffe_1_Wert":"",
					"Waffe_2_Wert":"",
					"Waffe_2_Fertigkeit":"",
					"Waffe_3_Fertigkeit":"",
					"Waffe_4_Fertigkeit":"",
					"Schild_Fertigkeit":"",
					"Waffe_1_Fertigkeit":"",
					"Waffenlos_Fertigkeit":"",
					"Waffe_1_Att1":"",
					"Waffe_1_Att2":"",
					"Waffe_2_Att1":"",
					"Waffe_3_Att1":"",
					"Waffe_2_Att2":"",
					"Waffe_4_Att1":"",
					"Waffe_4_Att2":"",
					"Waffe_3_Att2":"",
					"Waffe_1_mod":"",
					"Waffe_2_mod":"",
					"Waffe_3_mod":"",
					"Waffe_4_mod":"",
					"Waffe_1_WGS":"",
					"Waffenlos_WGS":"",
					"Waffe_2_WGS":"",
					"Waffe_3_WGS":"",
					"Waffe_4_WGS":"",
					"Waffenlos_Schaden":"",
					"Waffe_2_Schaden":"",
					"Waffe_3_Schaden":"",
					"Waffe_4_Schaden":"",
					"Waffe_1_Schaden":"",
					"Waffe_4_Merkmale":"",
					"Waffe_2_Merkmale":"",
					"Waffe_3_Merkmale":"",
					"Waffe_1_Merkmale":"",
					"Schild_mod":"",
					"Schild_VTD+":"",
					"Schild_Merkmale":"",
					"Kampfmeisterschaft.0":"",
					"Kampfmeisterschaft.1":"",
					"Kampfmeisterschaft.2":"",
					"Kampfmeisterschaft.3":"",
					"Wirkung_3.0":"",
					"Wirkung_3.1":"",
					"Wirkung_3.2":"",
					"Wirkung_3.3":"",
					"Schw_2.0":"",
					"Schw_2.1":"",
					"Schw_2.2":"",
					"Schw_2.3":"",
					"Fertigk_2.0":"",
					"Fertigk_2.1":"",
					"Fertigk_2.2":"",
					"Fertigk_2.3":"",
					"Wirkung_2.0":"",
					"Wirkung_2.1":"",
					"Wirkung_2.2":"",
					"Wirkung_2.3":"",
					"Kampfmeisterschaft_2.0":"",
					"Kampfmeisterschaft_2.1":"",
					"Kampfmeisterschaft_2.2":"",
					"Kampfmeisterschaft_2.3":"",
					"Schw_3.0":"",
					"Schw_3.1":"",
					"Schw_3.2":"",
					"Schw_3.3":"",
					"Fertigk_3.0":"",
					"Fertigk_3.1":"",
					"Fertigk_3.2":"",
					"Fertigk_3.3":"",
					"Atemholen_benutzt":"",
					"Lunare":"",
					"Kupfer":"",
					"Vermögen_4":"",
					"Vermögen_5":"",
					"Solare":"",
					"Magieschule_1":"",
					"Magieschule_2":"",
					"Magieschule_3":"",
					"Magieschule_4":"",
					"Magieschule_5":"",
					"Magieschule_6":"",
					"Magieschule_1_Wert":"",
					"Magieschule_2_Wert":"",
					"Magieschule_3_Wert":"",
					"Magieschule_4_Wert":"",
					"Magieschule_5_Wert":"",
					"Magieschule_6_Wert":"",
					"Magieschule_1_Punkte":"",
					"Magieschule_2_Punkte":"",
					"Magieschule_3_Punkte":"",
					"Magieschule_4_Punkte":"",
					"Magieschule_5_Punkte":"",
					"Magieschule_6_Punkte":"",
					"Magieschule_2_Att2":"",
					"Magieschule_3_Att2":"",
					"Magieschule_4_Att2":"",
					"Magieschule_5_Att2":"",
					"Magieschule_6_Att2":"",
					"Magieschule_1_mod":"",
					"Magieschule_2_mod":"",
					"Magieschule_3_mod":"",
					"Magieschule_4_mod":"",
					"Magieschule_5_mod":"",
					"Magieschule_6_mod":"",
					"Magieschule_1_Att2":"",
					"Waffe_3_Wert":"",
					"Waffe_4_Wert":"",
					"Schild_Wert":"",
					"GW_temp":""
				};
				
			}, writeData = function(data, name){
				var destFile = path.join(destPDFPath, 'Splittermond_Charakterbogen_'+name+'.pdf');
				pdfFiller.fillForm(formFile, destFile, data, function(err){});
			};

		checkDirectory();
		
		return{
			getTemplate : getTemplate,
			mapTemplate : mapTemplate,
			writeData : writeData
		}
	};
	
module.exports = PDFCHARAKTERBOGEN();